apiVersion: v1
kind: ServiceAccount
metadata:
  name: a10-sa-default-ns
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: th-secret-rbac
subjects:
- kind: ServiceAccount
  name: a10-sa-default-ns
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
